version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: glassfish-dockerfile
    ports:
      - 18080:8080
      - 14848:4848

  db:
    image: mysql:5.6.47
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 38080:8080
